[redis]
addr="localhost:6380"

[plat]
addr="localhost:50010"
stdout="/var/log/pemgr-plat.out"
stderr="/var/log/pemgr-plat.err"
imp_mode=2

[autofan]
addr="localhost:50011"

[server]
http_enable=true
http_addr=":8081"
https_enable=true
https_addr=":8082"
basic_auth_user="admin"
basic_auth_password="irene"
certs="/etc/nginx"
stdout="/var/log/pemgr-server.out"
stderr="/var/log/pemgr-server.err"

